### ISSUE TITLE
weasyprint write_pdf got stuck

### ISSUE THREAD

**Issue by ghost** [fuergaosi233/gitbook2pdf#13]
https://github.com/fuergaosi233/gitbook2pdf/blob/3339b875d18f931c5cb2995a0f570cc32fe53da4/gitbook.py#L176

这个位置可能跑不动并且没有报错。

使用：

```
python: 3.7.2
url: https://learnyoua.haskell.sg/content/zh-cn/ch01/introduction.html
```

**Comment by fuergaosi233** [comment]
不好意思 忘了增加说明了
这个不是卡着了 是文件太大了 生成需要时间
由于`weasyprint`自身的问题
https://github.com/Kozea/WeasyPrint/issues/578
文件大小跟生成时间非线性相关
越大的文件需要的时间越多
我们正在增加分片生成的功能
或者换一个引擎来生成
