### ISSUE TITLE
pdf output 乱码

### ISSUE THREAD

**Issue by owen800q** [fuergaosi233/gitbook2pdf#24]
> /gitbook2pdf # python gitbook.py http://self-publishing.ebookchain.org
/usr/local/lib/python3.6/site-packages/weasyprint/document.py:34: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/3-电子书的生成.html
crawling :  http://self-publishing.ebookchain.org/5-附录/1-关于作者.html
crawling :  http://self-publishing.ebookchain.org/1-干嘛要写书？/2-写书的好处/readme.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/4-电子书的发布.html
crawling :  http://self-publishing.ebookchain.org/2-什么是自出版平台？/readme.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/readme.html
crawling :  http://self-publishing.ebookchain.org/4-最佳实践/妙手偶得无须刻意.html
crawling :  http://self-publishing.ebookchain.org/index.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/1-Summary的安装.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/2-Summary的使用.html
crawling :  http://self-publishing.ebookchain.org/5-附录/0-参考信息.html
crawling :  http://self-publishing.ebookchain.org/1-干嘛要写书？/1-写书的必要性/readme.html
done :  http://self-publishing.ebookchain.org/2-什么是自出版平台？/readme.html
done :  http://self-publishing.ebookchain.org/1-干嘛要写书？/1-写书的必要性/readme.html
done :  http://self-publishing.ebookchain.org/index.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/3-电子书的生成.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/1-Summary的安装.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/readme.html
done :  http://self-publishing.ebookchain.org/5-附录/0-参考信息.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/2-Summary的使用.html
done :  http://self-publishing.ebookchain.org/4-最佳实践/妙手偶得无须刻意.html
done :  http://self-publishing.ebookchain.org/5-附录/1-关于作者.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/4-电子书的发布.html
done :  http://self-publishing.ebookchain.org/1-干嘛要写书？/2-写书的好处/readme.html
crawl : all done!
Generating pdf,please wait patiently
Generated
![Screenshot from 2019-03-11 15-00-49](https://user-images.githubusercontent.com/19252045/54105795-193ae880-440f-11e9-94da-88da8a82c871.png)

**Comment by muyixi315** [comment]
请问这个中文乱码怎么解决？
