### ISSUE TITLE
无法抓取公式

### ISSUE THREAD

**Issue by jagger2048** [fuergaosi233/gitbook2pdf#28]
Bug 描述：
用 gitbook2pdf 工具将在线文档转成 pdf，在生成的 pdf 中，所有的公式均无法显示，初步推测解析和生成过程中出现了一些 bug， 导致 weasyprint  未能将公式进行转化导致无法显示数学公式。也有可能是 gitbook 所使用的 markdown 公式解析 js 在解析公式时有所延时导致。

Bug 复现：
python gitbook.py https://shichaog1.gitbooks.io/hand-book-of-speech-enhancement-and-recognition/content/
对比 
https://shichaog1.gitbooks.io/hand-book-of-speech-enhancement-and-recognition/content/chapter5.html
和 所生成的pdf 对应章节，网页版所有的公式在 pdf 中均无法显示

**Comment by liaochangjiang** [comment]
我禁用 https://shichaog1.gitbooks.io/hand-book-of-speech-enhancement-and-recognition/content/chapter5.html 页面的 JS （Developer Tools -> settings -> Debugger -> Disable Javascript）之后，发现公式不见了。

![image](https://user-images.githubusercontent.com/35447896/54868086-937e4c00-4dc3-11e9-9e3b-89b2472b913e.png)

说明这个公式的生成不知依赖于 CSS 文件，还和 JS 有关。

而目前的输出 PDF 引擎weasyprint无法对 JS 进行解析，所以此问题暂时无解。

**Comment by jagger2048** [comment]
那就有点遗憾了，除了无法解析 js 之外，  PDF 引擎 weasyprint 在生成 pdf
时消耗的时间和资源都蛮多的，以后要是有改进的话这个也留意一下。
