### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jason0539** [fuergaosi233/gitbook2pdf#29]
python gitbook.py http://book.flutterchina.club
报错
ClientConnectorCertificateError: Cannot connect to host book.flutterchina.club:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)')]

**Comment by fuergaosi233** [comment]
无法重现 这个报错可能是本地证书问题 我觉得你应该检测一下本地的根证书
