### ISSUE TITLE
参照教程安装后 , 报语法错误 .

### ISSUE THREAD

**Issue by keepthinkingit** [fuergaosi233/gitbook2pdf#30]
python gitbook.py https://*.com
```
  File "gitbook.py", line 220
    string = f"<h1 class='{class_}'>{title}</h1>"
                                                ^
SyntaxError: invalid syntax

```
本地环境 :
debian 9 , python3 , virtualenv .

**Comment by yilovezy** [comment]
windows python3 环境下也报上述错误

**Comment by fuergaosi233** [comment]
f-strings 是在3.6以后支持的 所以请确定你的python版本>=3.6 或者不使用fstring

**Comment by keepthinkingit** [comment]
> f-strings 是在3.6以后支持的 所以请确定你的python版本>=3.6 或者不使用fstring

非常感谢 , 切换版本后正常运行 . 
**推荐使用 pyenv**
