### ISSUE TITLE
按教程win10 64bit 执行py报错

### ISSUE THREAD

**Issue by CyfforPro** [fuergaosi233/gitbook2pdf#33]
严格按教程操作的
报错信息：
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2', 'cairo.so.2')
  File "C:\Users\Qinvz\AppData\Local\Programs\Python\Python37\lib\site-packages\cairocffi\__init__.py", line 36, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2
环境：
win10 1809 64bit
python 3.7.3
pip 19.0.3

**Comment by bituplink** [comment]
我也遇到了相同问题,但是我找到大概的原因了,我查到的是weasyprint依赖GTK组件,而window普遍支持不好,想装不容易,我估计源代码作者是Linux系统的,自带了GTK组件,不用安装

**Comment by bituplink** [comment]
有兴趣可以看下,就在官网
https://weasyprint.readthedocs.io/en/stable/install.html#windows
但是Windows真难安装
