### ISSUE TITLE
`pip3 install -r requirements.txt`报错 mac

### ISSUE THREAD

**Issue by amber-moe** [fuergaosi233/gitbook2pdf#47]
![image](https://user-images.githubusercontent.com/42762957/67179098-ce06a080-f407-11e9-932e-bcd057fae48e.png)

**Comment by enokoneko** [comment]
我也遇到了

**Comment by kataras** [comment]
Same here, windows 10 x64 (1903).

![ewq](https://user-images.githubusercontent.com/22900943/68496588-66e84900-025b-11ea-99ab-54927fe90345.png)

**Comment by fuergaosi233** [comment]
@Amber1990Zhang @edok10   you need to run `cd ./gitbook2pdf `  then run `pip3 install -r requirements.txt`

**Comment by fuergaosi233** [comment]
@kataras you need to install requests, you can run `pip3 install -r requirements.txt` to resolve dependencies .

**Comment by kataras** [comment]
I did it but the error still exists. But don't bother, I've edited the source code of the original gitbookIO repository locally and it works like a charm. Thanks for your reply anyways! Keep up the good work

**Comment by enokoneko** [comment]
> @Amber1990Zhang @edok10 you need to run `cd ./gitbook2pdf ` then run `pip3 install -r requirements.txt`

安装后依然无法运行
FMA-Danis:gitbook2pdf danis$ python gitbook.py https://spiketren.gitbooks.io/psy101
  File "gitbook.py", line 14
    async def request(url, headers, timeout=None):
            ^
SyntaxError: invalid syntax
FMA-Danis:gitbook2pdf danis$ pip3 gitbook.py https://spiketren.gitbooks.io/psy101
ERROR: unknown command "gitbook.py"
FMA-Danis:gitbook2pdf danis$ pip3 /Users/danis/gitbook2pdf/gitbook.py https://spiketren.gitbooks.io/psy101
ERROR: unknown command "/Users/danis/gitbook2pdf/gitbook.py"

**Comment by fuergaosi233** [comment]
@edok10 
Python 3.5 才加入async/await
请确定你的版本大于3.5

**Comment by enokoneko** [comment]
> @edok10
> Python 3.5 才加入async/await
> 请确定你的版本大于3.5

应该不是python的问题？

```
FMA-Danis:~ danis$ pip3 -V
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
FMA-Danis:~ danis$ cd ./gitbook2pdf
FMA-Danis:gitbook2pdf danis$ pip3 install -r requirements.txt
Requirement already satisfied: aiohttp==3.5.4 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.5.4)
FMA-Danis:gitbook2pdf danis$ pip3 gitbook.py
ERROR: unknown command "gitbook.py"
FMA-Danis:gitbook2pdf danis$ 
```

**Comment by fuergaosi233** [comment]
> > @edok10
> > Python 3.5 才加入async/await
> > 请确定你的版本大于3.5
> 
> 应该不是python的问题？
> 
> ```
> FMA-Danis:~ danis$ pip3 -V
> pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
> FMA-Danis:~ danis$ cd ./gitbook2pdf
> FMA-Danis:gitbook2pdf danis$ pip3 install -r requirements.txt
> Requirement already satisfied: aiohttp==3.5.4 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.5.4)
> FMA-Danis:gitbook2pdf danis$ pip3 gitbook.py
> ERROR: unknown command "gitbook.py"
> FMA-Danis:gitbook2pdf danis$ 
> ```

pip3 只是包管理工具工具 你看下`Readme`， 要用`python`进行运行的 （我会重写readme的

**Comment by amber-moe** [comment]
> @Amber1990Zhang @edok10 you need to run `cd ./gitbook2pdf ` then run `pip3 install -r requirements.txt`

I'm in the right directory but it still won't work.
The follow two won't work either.
`pip3 install requirements.txt --user`
`sudo pip3 install requirements.txt`

**Comment by fuergaosi233** [comment]
> > @Amber1990Zhang @edok10 you need to run `cd ./gitbook2pdf ` then run `pip3 install -r requirements.txt`
> 
> I'm in the right directory but it still won't work.
> The follow two won't work either.
> `pip3 install requirements.txt --user`
> `sudo pip3 install requirements.txt`
You need add`-r` for install all packages.
use `sudo pip3 install -r requirements.txt` instead of `sudo pip3 install requirements.txt`

**Comment by amber-moe** [comment]
> sudo pip3 install -r requirements.txt

Thank you, it works.

**Comment by amber-moe** [comment]
Thanks for replying, but I have a new problem
![image](https://user-images.githubusercontent.com/42762957/69201363-01f4f300-0b79-11ea-9408-8e12811c5864.png)

**Comment by fuergaosi233** [comment]
@Amber1990Zhang 
I think you need to reinstall `weasyprint` according to the document,because pip can't normal install `weasyprint`.
I will write a new `readme` on today.

**Comment by amber-moe** [comment]
> @Amber1990Zhang
> I think you need to reinstall `weasyprint` according to the document,because pip can't normal install `weasyprint`.
> I will write a new `readme` on today.

Thank you, will retry with your new README.
