### ISSUE TITLE
macOSX python 3.7 报错

### ISSUE THREAD

**Issue by Akateason** [fuergaosi233/gitbook2pdf#62]
python3 gitbook.py http://self-publishing.ebookchain.org

Traceback (most recent call last):
  File "gitbook.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by fuergaosi233** [comment]
You need to run `pip install -r requirements.txt`.

**Comment by spartucus** [comment]
So pip3 is not supported yet?
