### ISSUE TITLE
File "gitbook.py", line 14     async def request(url, headers, timeout=None):             ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by oPiZiL** [fuergaosi233/gitbook2pdf#64]
File "gitbook.py", line 14
    async def request(url, headers, timeout=None):
            ^
SyntaxError: invalid syntax

**Comment by fuergaosi233** [comment]
https://stackoverflow.com/questions/43948454/python-invalid-syntax-with-async-def
