### ISSUE TITLE
为什么导出的pdf是空白？

### ISSUE THREAD

**Issue by chengangc** [fuergaosi233/gitbook2pdf#65]
你好！
我在使用的时候，导出gitbook上的书的时候，显示为空白。
然后我就尝试示例：
python gitbook.py http://self-publishing.ebookchain.org

但是output产生的文件还是空白文档：
-rw-rw-r-- 1    340 7月  10 08:58  NetworkError.html
-rw-rw-r-- 1    939 7月  10 08:58  NetworkError.pdf

请问产生这个问题的可能原因是什么？谢谢！

**Comment by fuergaosi233** [comment]
这个网站无法访问 这个报错看起来是没有成功访问导致的
