### ISSUE TITLE
Could not find a version that satisfies the requirement get==2019.4.13

### ISSUE THREAD

**Issue by tainenko** [fuergaosi233/gitbook2pdf#66]
ERROR: Could not find a version that satisfies the requirement get==2019.4.13 (from -r requirements.txt (line 13)) (from versions: none)
ERROR: No matching distribution found for get==2019.4.13 (from -r requirements.txt (line 13))

**Comment by jysui123** [comment]
Got similar error:
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/get/

**Comment by gouchaoer** [comment]
same

**Comment by ziventian** [comment]
Same error.
I just comment those lines ends with 2019.4.13, and it works.

**Comment by ccforeverd** [comment]
same error.

``` bash
$ which pip3
/Library/Frameworks/Python.framework/Versions/3.7/bin/pip3
```
